_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Detection/retinanet_R_50_FPN_3x/137849486/model_final_4cafe0.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("geom-original-train",)
  TEST: ("geom-original-test",)
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 2
  MAX_ITER: 1000
DATALOADER:
  NUM_WORKERS: 1